version: '3.6'

services:

  redis:
    image: "redis:alpine"
    hostname: "redis"
    ports:
      - "6379:6379"

  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - redis